---
- hosts: localhost
  vars_files:
    - network_configs.yml

  tasks:
  - name: Define the network
    virt_net:
      command: define
      name: '{{ network[item].network_name }}'
      xml: '{{ lookup("template", "templates/bridge.xml.j2") }}'
      state: present
    with_items: "{{ network }}"
    become: yes

  - name: Create the network
    virt_net:
      command: create
      name: '{{ network[item].network_name }}'
      autostart: true
    with_items: "{{ network }}"
    ignore_errors: true
    become: yes

#  - name: Start the network
#    virt_net:
#      command: start
#      name: '{{ network_name }}'
#
#  - name: Show networks
#    virt_net:
#      command: list_nets
#    register: out
#  - debug: var=out
