---
- hosts: localhost
  vars:
    bridge_name: 'ovs-br1'
    network_name: 'pmallya-netl3'

  tasks:
  - name: Define the network
    virt_net:
      command: define
      name: '{{ network_name }}'
      xml: '{{ lookup("template", "templates/pmallya-netl3.xml.j2") }}'
      state: present

  - name: Create the network
    virt_net:
      command: create
      name: '{{ network_name }}'
      autostart: true
    ignore_errors: true

  - name: Start the network
    virt_net:
      command: start
      name: '{{ network_name }}'

  - name: Show networks
    virt_net:
      command: list_nets
    register: out
  - debug: var=out
