---
- hosts: localhost
  vars:
    bridge_name: 'ovs-br1'

  tasks:
  - name: Creating OVS bridge
    openvswitch_bridge:
      bridge: '{{ bridge_name }}'
      state: present
  
  - command: '{{ item }}'
    with_items:
    - ip addr add 2.2.2.2/24 dev '{{ bridge_name }}'
    - ip link set 
'{{ bridge_name }}' up
    ignore_errors: yes
