---
- hosts: localhost
  vars:
    result: 0
  vars_files:
    - network_configs.yml

  tasks:
  - name: Define the network
    virt_net:
      command: define
      name: '{{ item.network_name }}'
      xml: '{{ lookup("template", "templates/bridge.xml.j2") }}'
      state: present
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"
    become: yes

  - name: Create the network
    virt_net:
      command: create
      name: '{{ item.network_name }}'
      autostart: true
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"
    become: yes

  - name: Assign IP addresses to non bridge devices
    command: "ip addr add {{ item.ip_address }}/{{ item.subnet_mask_num }} dev {{ item.bridge_name }}"
    when: 
      - item.bridge_type != "bridge"
      - (ansible_facts[item.bridge_name]['ipv4'] is not defined) or (ansible_facts[item.bridge_name]['ipv4']['address'] != item.ip_address)
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"
    become: yes

  - name: Create DNS server for DHCP bridges
    command: "dnsmasq --interface={{ item.bridge_name }} --bind-interfaces --dhcp-range={{ item.dhcp_start_range }},{{ item.dhcp_end_range }},{{ item.dhcp_lease_time }}"
    when: 
      - '"dhcp" in item.bridge_type'
    ignore_errors: true
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"
    become: yes

  - name: Adding NAT functionality to NAT bridges
    iptables:
      table: nat
      chain: POSTROUTING
      action: append
      state: present
      source: "{{ item.subnet_address }}/{{ item.subnet_mask_num }}"
      jump: MASQUERADE
    when:
      - '"nat" in item.bridge_type'
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"
    become: yes

  - name: Start the network
    virt_net:
      command: start
      name: '{{ item.network_name }}'
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"
    become: yes
    
  - name: Show networks
    virt_net:
      command: list_nets
    register: out
  - debug: var=out
