---
- hosts: localhost
  vars_files:
    - network_configs.yml

  tasks:
  - name: Creating OVS bridge
    openvswitch_bridge:
      bridge: "{{ network[item].bridge_name }}"
      state: present
    with_items: "{{ network }}"

  - name: Set the bridges UP
    command: "ip link set {{ network[item].bridge_name }} up"
    with_items: "{{ network }}"
