---
- hosts: localhost
  
  vars_files:
    - vm_configs.yml
    - network_configs.yml

  tasks:
  - name: Parse VM data
    template:
      src: vm.j2 
      dest: "{{item.name}}_interfaces.txt"
    with_items: "{{ vms }}"
     
#  tasks:
#  - name: Define VMs
#    virt:
#      name: "{{ item.name }}"
#      command: define
#      xml: "{{ lookup('template', 'templates/vm.xml.j2') }}"
#    with_items: "{{ params }}"
#
#  - name: Create VM
#    virt:
#      name: "{{ item.name }}"
#      command: create
#      state: destroyed
#    with_items: "{{ params }}"
#
#  - name: Start VM
#    virt:
#      name: "{{ item.name }}"
#      command: start
#    with_items: "{{ params }}"
