---
- hosts: localhost
  vars_files:
    - network_configs.yml

  tasks:
  - name: Creating OVS bridge
    openvswitch_bridge:
      bridge: "{{ item.bridge_name }}"
      state: present
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"

  - name: Set the bridges UP
    command: "ip link set {{ item.bridge_name }} up"
    with_items: 
      - "{{ network.internet }}"
      - "{{ network.l2 }}"
      - "{{ network.l3 }}"
      - "{{ network.other }}"
