---
- hosts: localhost
  vars:
    bridge_name: 'ovs-br1'
    network_name: 'pmallya-netl3'
    
    params:
      - name: pmallya10
        ram: 2097152
        vcpu: 4
       # size: 10
        iso: /home/ece792/images/CentOS-7-x86_64-Minimal-1908.iso 
        path: /var/lib/libvirt/images/pmallya10.img
        id: 59
        dev: vnet5
        alias: net5
        mac: 00:bb:cb:db:eb:fb
        mac_def: 00:bb:cc:dd:ee:ff
    
  tasks:
  - name: Create VMs
    virt:
      name: "{{ item.name }}"
      command: define
      xml: "{{ lookup('template', 'templates/vm.xml.j2') }}"
    with_items: "{{ params }}"

  - name: Start VM
    virt:
      name: "{{ item.name }}"
      command: create
    with_items: "{{ params }}"
