---
- hosts: localhost
  vars_files:
    - network_configs.yml

  tasks:
  - name: Creating OVS bridge
    openvswitch_bridge:
      bridge: "{{ network[item].bridge_name}}"
      state: present
    with_items: "{{ network }}"


#  - command: '{{ item }}'
#    with_items:
#    - ip addr add 2.2.2.2/24 dev '{{ bridge_name }}'
#    - ip link set '{{ bridge_name }}' up
#    ignore_errors: yes
