---
- hosts: localhost
  
  vars_files:
    - vm_configs.yml
    - network_configs.yml

  tasks:
  - name: Parse VM data
    template:
      src: vm.j2 
      dest: "{{item.name}}_interfaces.xml"
    with_items: "{{ vms }}"

  - name: Create VM templates
    copy:
      src: templates/vm.xml.j2
      dest: templates/VM_Templates/{{item.name}}.xml.j2
    with_items: "{{ vms }}"

  - name: Populate VM templates
    blockinfile:
      path: templates/VM_Templates/{{item.name}}.xml.j2
      marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
      insertbefore: "<serial type='pty'>"
      block: "{{ lookup('file', '{{item.name}}_interfaces.xml') }}"
      backup: yes
    with_items: "{{ vms }}"

  
#  tasks:
#  - name: Define VMs
#    virt:
#      name: "{{ item.name }}"
#      command: define
#      xml: "{{ lookup('template', 'templates/vm.xml.j2') }}"
#    with_items: "{{ params }}"
#
#  - name: Create VM
#    virt:
#      name: "{{ item.name }}"
#      command: create
#      state: destroyed
#    with_items: "{{ params }}"
#
#  - name: Start VM
#    virt:
#      name: "{{ item.name }}"
#      command: start
#    with_items: "{{ params }}"
