---
- hosts: localhost
  tasks:
  - name: Install libvirt packages if necessary
    apt:
      name:
      - qemu-kvm
      - libvirt-bin
      - python-libvirt
      - python-lxml
      - virt-manager
      - virt-viewer
      - virtinst
      - apache2
      - network-manager
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Installing OVS
    apt:
      name:
      - openvswitch-switch
      state: present
