---
  network:
    internet:
      network_name: internet
      bridge_name: SW1
      bridge_type: nat/dhcp
      ip_address: 9.9.9.1/24
      dhcp_range: 9.9.9.2,9.9.9.255
      subnet_address: 9.9.9.0/24
    l2:
      network_name: l2
      bridge_name: SW2
      bridge_type: bridge
    l3:
      network_name: l3
      bridge_name: SW3
      bridge_type: routed
      ip_address: 10.10.10.1/24
    other:
      network_name: other
      bridge_name: SW4
      bridge_name: routed
      ip_address: 11.11.11.1/24
