---
  vms:
    - name: AnsibleVM1
      mem: 512
      vcpu: 1
      disk: 12G
      networks: ["internet", "l2" ]
    
    - name: AnsibleVM2
      mem: 512
      vcpu: 1
      disk: 12G
      networks: ["l2", "l3" ]
